export const CANVAS_WIDTH = 800;
export const CANVAS_HEIGHT = 600;
export const PLAYER_SIZE = 64;
export const PLAYER_SPEED = 200;
export const PLAYER_BOOST_SPEED = 350;
export const TREAT_SIZE = 24;
export const CAT_SIZE = 48; // Bigger cats!
export const BONE_SIZE = 32;
export const POWERUP_SIZE = 30;
export const SQUIRREL_SIZE = 36;
export const TREAT_POINTS = 10;
export const CAT_POINTS = 50;
export const BONE_POINTS = 25;
export const SQUIRREL_POINTS = 75;
export const MAX_TREATS = 10;
export const MAX_CATS = 2;
export const MAX_BONES = 3;
export const MAX_POWERUPS = 2;
export const MAX_SQUIRRELS = 2;
export const POWERUP_DURATION = 5; // seconds